### ISSUE TITLE
Doesn't validate required fields

### ISSUE THREAD

**Issue by aabutaleb** [RobWin/assertj-swagger#13]
In my case, I've got an object that had a field incorrectly declared as required

*/v2/api-docs generated JSON*

```javascript
"ClassA": {
    "type": "object",
    "required": [
         "field1"
          ]
     ...
     }
```

And this is what the actual YAML contract has in it:

```
ClassA:
    properties:
      field1:
        $ref: "#/definitions/Class1"
      field2:
        type: "integer"
        format: "int64"
      field3:
        type: "boolean"
```

And this is my Java test class:

```java
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@RunWith(SpringRunner.class)
public class ApplicationTests {

	@LocalServerPort
	int serverPort;

	@Test
	public void contextLoads() {
	}

	@Test
	public void validateThatImplementationMatchesDocumentedSpecification() throws URISyntaxException {
		String designFirstSwagger = Paths.get(ApplicationTests.class.
				getResource("/spec/swagger.yaml").toURI()).toString();
		SwaggerAssertions.assertThat("http://localhost:"+serverPort+"/v2/api-docs?group=Api")
				.isEqualTo(designFirstSwagger);
	}
}
```

**Comment by RobWin** [comment]
Hi,

woud you like to create a PR?

**Comment by aabutaleb** [comment]
Hi, 

I haven't fixed it yet, first I wanted to check whether this is a config thing I'm missing or there's any reason why it doesn't check that the required fields are the same.

**Comment by RobWin** [comment]
No sry, this check is not implemented yet.

**Comment by aabutaleb** [comment]
@RobWin I see here the problem is that the `Model` interface doesn't expose the a *getRequired()* method, which only exists in the ModelImpl class :(

**Comment by RobWin** [comment]
You could add it here: https://github.com/RobWin/assertj-swagger/blob/master/src/main/java/io/github/robwin/swagger/test/DocumentationDrivenValidator.java#L124
