### ISSUE TITLE
swagger-compat-spec-parser dependency should be latest - https://github.com/swagger-api/swagger-parser/issues/39

### ISSUE THREAD

**Issue by rajeshkamal** [RobWin/assertj-swagger#2]

**Comment by RobWin** [comment]
Hi thx. Feel free to create a PR.

**Comment by RobWin** [comment]
If you use Swagger and Springfox, have a look at https://github.com/Swagger2Markup/swagger2markup

**Comment by rajeshkamal** [comment]
Thanks @RobWin, I am already using Swagger and Sprinfox springfox-staticdocs with Swagger2markup.

I bumped into an issue when using using the assertj-swagger for the swagger spec checks.

I believe springfox-staticdocs has dependency with swagger-compat-spec-parser and which in turn with swagger-parser with version 1.0.13.

But when I use assertj-statisdocs it has dependency with 1.0.8 and was running into an issue reported here - https://github.com/swagger-api/swagger-parser/issues/39

**Comment by RobWin** [comment]
Yes. I update the dependency on monday.
If you use Swagger2markup, I would love to get your GitHub Star  :)

**Comment by rajeshkamal** [comment]
Done... thanks @RobWin

**Comment by RobWin** [comment]
I published v0.1.3.
The swagger-parser is updated to v1.0.16
