### ISSUE TITLE
Release 0.8.1

### ISSUE THREAD

**Issue by joerupen** [RobWin/assertj-swagger#50]
Hi,

I saw that on master there's already a commit to fix the dependency on assertj 2.9.1. Is it possible that you release a new version with this patch?

**Comment by marcelstoer** [comment]
> fix the dependency on assertj 2.9.1

Make that assertj **3**.9.1... We're also eagerly looking forward to a new release (@RobWin we know you're looking for a maintainer).

**Comment by RobWin** [comment]
I've released v0.8.1

**Comment by marcelstoer** [comment]
Thanks! So, the only thing missing is the tag/release on GH? I see it on Bintray.

**Comment by RobWin** [comment]
Yes. Maven central sync might take a while.
